### ISSUE TITLE
Format of detections for VitPose?

### ISSUE THREAD

**Issue by AJDA1992** [gpastal24/ViTPose-Pytorch#2]
Are the bounding boxes when extracting the image patches to be inputs into vit in the form x1,y1,x2,y2 or aare they converted to tlwh format?

Also what is the purpose of the correction factor in the pose_utils.py file?

**Comment by gpastal24** [comment]
Hi, the correction factor aims to keep the correct aspect ratio that the pose model was trained on to produce better results. It is a basic zero padding either in the y or x axis. 

The bounding boxes from yolov5 are in xyxy format, bytetracker converts these bounding boxes to tlwh format ( they can be retrieved in xyxy format as well), but the boxes to extract the patches are in xyxy.

After cropping the image in the desired aspect ratio with zero padding, the patches are interpolated to 256x192 (y,x) resolution and fed to the model. Basically you have to provide the ViTPose model with already cropped, resized and normalized input, as in other top-down methods.

Please note that this is not the official implementation, I created this repository since I did not want to use mmcv.

**Comment by AJDA1992** [comment]
@gpastal24  Thnks for the quick response! So just so I am clear, the sub image patches are extracted using xyxy format but the correction factor is applied to the tlwh format from the output of bytetrack?

**Comment by gpastal24** [comment]
No, they are both in xyxy format. 

`for i, (x1, y1, x2, y2) in enumerate(online_tlwhs):

       x1 = x1.astype(np.int32)
      x2 = x1+x2.astype(np.int32)
      y1 = y1.astype(np.int32)
      y2 = y1+ y2.astype(np.int32)`

In these lines of the code in pose_utils the tlhw from the tracker is converted back to xyxy.

**Comment by gpastal24** [comment]
May I close this?
