### ISSUE TITLE
Train Scripts?

### ISSUE THREAD

**Issue by CapnBloodBeard12345** [gpastal24/ViTPose-Pytorch#4]
Do you have any plans to release a train script for this?

**Comment by gpastal24** [comment]
Not really, at least not at this time. This repo was created cause I wanted to test this method, and since it i easier to deploy with torch directly, at least for me, I made it public. I never had in my mind to write the training code as well.

 Although it should be easy to do it, using for example HRNet or Simple Baselines training code, ignoring their configs, loading the model with the pretrained backbone( so another functions should load only the VAE backbone weights instead of the whole network ) and making the necessary changes to their code.

If I remember correctly the official VitPose repo hasn't released their multi scale training code, so this approach should work fine.

**Comment by CapnBloodBeard12345** [comment]
Do they do a multiscale inference? I am assuming it functions like openpose's multiscale by fixing multiple resolutions then preforming an averaging operation on the heatmaps? 
Curious how they would achieve this with ViT given that it needs a fixed input resolution?

**Comment by gpastal24** [comment]
You are correct, they do training in multiple datasets, not multi-scale training. My bad
